name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping
        run: |
          curl https://instatodrive.onrender.com/health
